# Generated by Django 3.0.8 on 2020-09-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.IntegerField(),
        ),
    ]
